accum_grad: 1
cmvn: global_cmvn
cmvn_conf:
  cmvn_file: /root/autodl-tmp/wenet/pretrained/global_cmvn
  is_json_cmvn: true
ctc: ctc
ctc_conf:
  ctc_blank_id: 0
dataset: asr
dataset_conf:
  batch_conf:
    batch_size: 16
    batch_type: static
  fbank_conf:
    dither: 1.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  filter_conf:
    max_length: 40960
    min_length: 0
    token_max_length: 200
    token_min_length: 1
  resample_conf:
    resample_rate: 16000
  shuffle: true
  shuffle_conf:
    shuffle_size: 1500
  sort: true
  sort_conf:
    sort_size: 500
  spec_aug: true
  spec_aug_conf:
    max_f: 10
    max_t: 50
    num_f_mask: 2
    num_t_mask: 2
  spec_sub: true
  spec_sub_conf:
    max_t: 30
    num_t_sub: 3
  spec_trim: false
  spec_trim_conf:
    max_t: 50
  speed_perturb: true
decoder: bitransformer
decoder_conf:
  attention_heads: 4
  dropout_rate: 0.1
  linear_units: 2048
  num_blocks: 3
  positional_dropout_rate: 0.1
  r_num_blocks: 3
  self_attention_dropout_rate: 0.1
  src_attention_dropout_rate: 0.1
dtype: fp32
encoder: conformer
encoder_conf:
  activation_type: swish
  attention_dropout_rate: 0.1
  attention_heads: 4
  causal: true
  cnn_module_kernel: 8
  cnn_module_norm: layer_norm
  dropout_rate: 0.1
  input_layer: conv2d
  linear_units: 2048
  normalize_before: true
  num_blocks: 12
  output_size: 256
  pos_enc_layer_type: rel_pos
  positional_dropout_rate: 0.1
  selfattention_layer_type: rel_selfattn
  use_cnn_module: true
  use_dynamic_chunk: true
  use_dynamic_left_chunk: false
epoch: 2
grad_clip: 5
input_dim: 80
log_interval: 100
loss_dict:
  acc: 0.7743053725787572
  loss: 11.66341847793879
  loss_att: 10.039685308276312
  loss_ctc: 15.452128977089508
lrs:
- 0.0003546
max_epoch: 360
model: asr_model
model_conf:
  ctc_weight: 0.3
  length_normalized_loss: false
  lsm_weight: 0.1
  reverse_weight: 0.3
model_dir: ./
optim: adam
optim_conf:
  lr: 0.001
output_dim: 4233
save_states: model_only
save_time: 19/06/2025 13:08:26
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 25000
step: 8865
tag: epoch_2
tokenizer: char
tokenizer_conf:
  bpe_path: null
  is_multilingual: false
  non_lang_syms_path: null
  num_languages: 1
  special_tokens:
    <blank>: 0
    <eos>: 2
    <sos>: 2
    <unk>: 1
  split_with_space: false
  symbol_table_path: /root/autodl-tmp/wenet/pretrained/units.txt
train_engine: torch_ddp
use_amp: false
vocab_size: 4233
